apiVersion: v1
kind: Service
metadata:
  name: movie-db
spec:
  clusterIP: None
  selector:
    app: movie-db
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: movie-db
spec:
  serviceName: movie-db
  replicas: 1
  selector:
    matchLabels:
      app: movie-db
  template:
    metadata:
      labels:
        app: movie-db
    spec:
      containers:
        - name: movie-db
          image: postgres:12.1-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "movie_db_username"
            - name: POSTGRES_PASSWORD
              value: "movie_db_password"
            - name: POSTGRES_DB
              value: "movie_db_dev"
          volumeMounts:
            - name: movie-db-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: movie-db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
